### ISSUE TITLE
How to download notebook files

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiTutorials#4]
Right now, there's no straightforward way to download a notebook or all notebooks. The question is, do we want people to be able to just download all tutorials? And if yes, in which form? Just the `.jl` files, or also the generated output files?

An easy first solution would be to just add a download button for the notebook next to nbviewer and mybinder, e.g.,
![img](https://img.shields.io/badge/download-notebook-brightgreen)

**Comment by bennibolm** [comment]
For now, I added a button to the generated `.ipynb` file. It's not downloaded directly, but opens in a tab where you can just save it. Do you know if there is a way to download it directly? Or do we even want that?
If this worked, a link to download all could be in the introduction part.

I think we don't need a link to download the `.jl` file, because you can just click on `Edit on GitHub`.

**Comment by sloede** [comment]
No, I agree, we don't need to download jl files individually. I was just wondering if we should add a tarball with all relevant files (eg, the jl, the MD, and the notbooks) to a release. But maybe that's not necessary right now and we should only do it if someone really asks for it.

I don't know of any other (better) way to download the notebook, so let's leave it like you did for now
